name: Sync extension test

on:
  push:
    branches:
      - 'main'
    paths:
      - .github/workflows/sync-extension-test.yml
      - workflow-templates/.github/workflows/extension-test.yml
      - workflow-templates/.github/workflows/create-pr-updating-extension-test.yml

jobs:
  copy:
    strategy:
      matrix:
        repository:
          - AchievementBadges
          - DiscordRCFeed
          - FacetedCategory
          - PageViewInfoGA
          - Sanctions
          - UnifiedExtensionForFemiwiki
        branch:
          - main
          - REL1_37
          - REL1_38

    runs-on: ubuntu-latest
    steps:
      - uses: GuillaumeFalourd/create-other-repo-branch-action@v1
        continue-on-error: true
        with:
          repository_owner: ${{ github.repository_owner }}
          repository_name: ${{ matrix.repository }}
          new_branch_name: update-extension-test-${{ matrix.branch }}
          new_branch_ref: ${{ matrix.branch }}
          access_token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Copycat
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          src_path: workflow-templates/.github/workflows/.
          src_branch: main
          dst_path: .github/workflows/.
          dst_owner: femiwiki
          dst_repo_name: ${{ matrix.repository }}
          dst_branch: update-extension-test-${{ matrix.branch }}
          commit_message: |
            ${{ github.event.head_commit.message }}

            from https://github.com/${{ github.event.repository.full_name }}/commit/${{ github.event.head_commit.id }}
